# Generated by Django 2.2.20 on 2021-05-01 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hindiblog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hindiblog',
            name='body',
        ),
        migrations.AddField(
            model_name='hindiblog',
            name='poem',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
