# Generated by Django 2.2.20 on 2021-05-03 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hindiblog', '0003_hindiblog_summary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hindiblog',
            old_name='summary',
            new_name='poem_text',
        ),
        migrations.RemoveField(
            model_name='hindiblog',
            name='poem',
        ),
    ]
