# Generated by Django 2.2.20 on 2021-06-21 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hindiblog', '0004_auto_20210503_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='hindiblog',
            name='likes_total',
            field=models.IntegerField(default=1),
        ),
    ]
