# Generated by Django 2.2.20 on 2021-04-30 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210428_1335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='edit_date',
        ),
        migrations.AlterField(
            model_name='blog',
            name='body',
            field=models.TextField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
