# Generated by Django 2.2.20 on 2021-05-01 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210430_1738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='body',
        ),
        migrations.AddField(
            model_name='blog',
            name='poem',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
