# Generated by Django 2.2.20 on 2021-05-03 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_blog_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='poem_text',
            field=models.TextField(max_length=2000, null=True),
        ),
    ]
