# Generated by Django 2.2.20 on 2021-05-03 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_blog_poem_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='poem',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='summary',
        ),
    ]
