# Generated by Django 2.2.20 on 2021-06-23 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20210503_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='likes_total',
            field=models.IntegerField(default=1),
        ),
    ]
