# Generated by Django 2.2.20 on 2021-06-23 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writings', '0002_auto_20210614_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='writings',
            name='likes_total',
            field=models.IntegerField(default=1),
        ),
    ]
